# https://taskfile.dev

version: '3'


vars:
  EXE: server{{exeExt}}


tasks:

  default:
    deps: [build:current]
    cmds:
      - ./{{.EXE}}

  dev:
    desc: Live restart server
    deps: [build:current]
    cmds:
      - go build -v ./cmd/server
      - ./{{.EXE}}
    sources:
      - ./**/*.go
      - ./**/*.tpl
      - ./**/*.tmpl
      - ./**/*.html
      - ./**/*.env

  build:
    desc: Build server for windows and linux
    deps: [build:windows, build:linux]

  build:current:
    desc: Build server for current os
    deps: [format]
    cmds:
      - go build -v ./cmd/server
    sources:
      - ./**/*.go
      - ./**/*.tpl
      - ./**/*.tmpl
      - ./**/*.html
      - ./**/*.env
  
  build:windows:
    desc: Build server for windows
    env:
      GOOS: windows
      GOARCH: amd64
    cmds: 
      - go build -v ./cmd/server
  
  build:linux:
    desc: Build server for windows
    env:
      GOOS: linux
      GOARCH: amd64
    cmds: 
      - go build -v ./cmd/server

  format:
    desc: Format sources
    cmds:
      - go fmt {{catLines .PACKAGES}}
    vars:
      PACKAGES:
        sh: go list ./...
    silent: true

  test:
    desc: Runs test server
    cmds:
      - go clean -testcache
      - go test {{catLines .PACKAGES}}
    vars:
      PACKAGES:
        sh: go list ./...
    silent: true

  mod:
    desc: Downloads and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy
  
  clean:
    desc: Cleans every generated file
    cmds:
      - rm -f {{.EXE}}