name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: QWEasd123
  POSTGRES_DB: devback
  TEST_DATABASE_URL: postgresql://root:QWEasd123@127.0.0.1:5432/devback
  

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Set up Task
      run: go install github.com/go-task/task/v3/cmd/task@latest

    - name: Build Server
      run: task build

    - name: Test Server
      env: 
        TEST_DATABASE_URL: ${{ env.TEST_DATABASE_URL }}
      run: task test
    
    
    
      
